permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: https://stage.gamecreation.org/
games_path: https://stage.gamecreation.org/games/

# Tags used for filtering games
game_tags: [
    # Platform
    "Windows", "Mac", "Linux", "Web", "Flash", "iOS", "Android", "Other",
    # Players
    "Singleplayer", "Multiplayer",
    # Engines
    "Unity", "Unreal", "Godot", "Pygame", "Twine", "Board",
    # Input methods
    "Controller-Compatible", "VR", "Kinect",
    # Extras
    "Game-Jam", "Independent"
]

# Plugins
plugins:
  - jekyll-redirect-from
