permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: https://stage.gamecreation.org/

# Tags used for filtering games
game_tags: [
    "Windows",                  "Mac",          "Linux",    "Web",   "Other",
    "Singleplayer",             "Multiplayer",
    "Controller-Compatible",    "VR",
    "Game-Jam", "Unity", "Unreal", "iOS", "Android"
]

# Plugins
plugins:
  - jekyll-redirect-from
