permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: http://stage.gamecreation.org/

# Tags used for filtering games
game_tags: [
    "Windows",                  "Mac",          "Linux",    "Online",   "Other",
    "Singleplayer",             "Multiplayer",
    "Controller-Compatible",    "VR",
    "Game-Jam"
]

# Plugins
plugins:
  - jekyll-redirect-from
