permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: https://stage.gamecreation.org/
games_path: https://stage.gamecreation.org/games/

# Tags used for filtering games
tag_lists: [
    {
        "id": "platform",
        "name": "Platform",
        "default": "Any",
        "tags": ["Windows", "Mac", "Linux", "Web", "iOS", "Android", "Console"]
    },
    {
        "id": "genre",
        "name": "Genre",
        "default": "Any",
        "tags": ["Arcade", "Fighting", "Horror", "Party", "Platformer", "Puzzle", "Rhythm", "Rougelike", "RPG", "Shooter", "Strategy", "Visual-Novel", "Untagged"]
    },
    {
        "id": "players",
        "name": "Players",
        "default": "Any",
        "tags": ["Singleplayer", "Multiplayer"]
    },
    {
        "id": "input_methods",
        "name": "Input Methods",
        "default": "Any",
        "tags": ["Controller-Compatible", "VR", "Kinect"]
    },
    {
        "id": "engine",
        "name": "Engine",
        "default": "Any",
        "tags": ["Unity", "Unreal", "Godot", "Flash", "Pygame", "Twine", "Board"]
    },
    {
        "id": "awards",
        "name": "Awards",
        "default": "",
        "tags": ["Award-Winning", "GCS Gold Award", "Best Art", "Best Music", "Best Tech", "Most Innovative Gameplay", "Schell Games Award", "People's Choice Award"]
    },
    {
        "id": "extras",
        "name": "Extras",
        "default": "",
        "tags": ["Game-Jam", "Independent"]
    }
]

# Plugins
plugins:
  - jekyll-redirect-from
