permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: https://stage.gamecreation.org/
games_path: https://stage.gamecreation.org/games/

# Tags used for filtering games
game_tags: [
    # Platform
    "Windows", "Mac", "Linux", "Web", "iOS", "Android", "Board", "Other",
    # Players
    "Singleplayer", "Multiplayer",
    # Engines
    "Unity", "Unreal", "Godot",
    # Extras
    "Controller-Compatible", "VR", "Game-Jam", "Independent"
]

# Plugins
plugins:
  - jekyll-redirect-from
