permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: http://stage.gamecreation.org/

# Tags used for filtering games
game_tags: [
    "Windows",                  "Mac",          "Linux",
    "Singleplayer",             "Multiplayer",
    "Controller-Compatible",    "VR",
    "Game-Jam"
]

# Update this once a class has graduated
last_graduated_year: 2018
