permalink: /:title
collections:
    games:
        output: true
        permalink: /games/:title
    members:
        output: true
        permalink: /members/:title

# The path to the stage directory in the gcs server, where builds are hosted
stage_path: https://stage.gamecreation.org/
games_path: https://stage.gamecreation.org/games/

# Tags used for filtering games
tag_lists: [
    {
        "id": "platform",
        "name": "Platform",
        "tags": ["Windows", "Mac", "Linux", "Web", "iOS", "Android", "Other"]
    },
    {
        "id": "players",
        "name": "Players",
        "tags": ["Singleplayer", "Multiplayer"]
    },
    {
        "id": "engine",
        "name": "Engine",
        "tags": ["Unity", "Unreal", "Godot", "Flash", "Pygame", "Twine", "Board"]
    },
    {
        "id": "input_methods",
        "name": "Input Methods",
        "tags": ["Controller-Compatible", "VR", "Kinect"]
    },
    {
        "id": "extras",
        "name": "Extras",
        "tags": ["Game-Jam", "Independent"]
    }
]

# Plugins
plugins:
  - jekyll-redirect-from
